package com.mesh_suite.constant.forms;

public enum Sector {
        AGRIBUSINESS, AGRO_PROCESSING, CONSTRUCTION, COMMERCE_AND_TRADE, EDUCATION,
        FASHION_AND_BEAUTY, FOOD_AND_BEVERAGE, HEALTHCARE_AND_PHARMACEUTICALS,
        MANUFACTURING, TECHNOLOGY_ICT, REAL_ESTATE_AND_CONSTRUCTION, RENEWABLE_ENERGY,
        SERVICES, TOURISM_AND_HOSPITALITY, TRANSPORTATION, WATER_AND_SANITATION
    }